-- MySQL Script generated by MySQL Workbench
-- 07/25/14 15:50:23
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `bdreportes` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bdreportes` ;

-- -----------------------------------------------------
-- Table `tbl_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_usuarios` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `prnombre` VARCHAR(50) NOT NULL,
  `sgnombre` VARCHAR(50) NULL,
  `prapellido` VARCHAR(50) NOT NULL,
  `sgapellido` VARCHAR(50) NULL,
  `clave` BINARY NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_ultimo_ingreso` DATETIME NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_apchck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_apchck` (
  `cchkno` VARCHAR(10) NOT NULL,
  `cvend` VARCHAR(10) NOT NULL,
  `cpayto` VARCHAR(40) NOT NULL,
  `cchktype` VARCHAR(1) NOT NULL,
  `cbankno` VARCHAR(10) NOT NULL,
  `ctogl` VARCHAR(10) NOT NULL,
  `dcheck` DATETIME NOT NULL,
  `dcreate` DATETIME NOT NULL,
  `lcancel` TINYINT NOT NULL,
  `lhold` TINYINT NOT NULL,
  `nchkamt` DECIMAL(16,2) NOT NULL,
  `nxchgrate` DECIMAL(16,2) NOT NULL,
  `nbchkamt` DECIMAL(16,2) NOT NULL,
  PRIMARY KEY (`cchkno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_rol` (
  `id_rol` SMALLINT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_rol_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_rol_usuario` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `id_rol` SMALLINT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre_departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_oficina` (
  `id_oficina` SMALLINT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `id_region` SMALLINT NOT NULL,
  PRIMARY KEY (`id_oficina`),
  UNIQUE INDEX `id_region_UNIQUE` (`id_region` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_region` (
  `id_region` SMALLINT NOT NULL AUTO_INCREMENT,
  `nombre_region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_region`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
